"""make_password_nullable_add_google_id

Revision ID: 0638b7f2ce00
Revises: 73087c42f8ec
Create Date: 2026-07-10 23:02:11.321413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0638b7f2ce00'
down_revision: Union[str, Sequence[str], None] = '73087c42f8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
